name: Deploy GitHub Pages

on:
  push:
    branches:
      - main # Or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      # If your site requires a build step (e.g., a static site generator)
      - name: Build site
        run: npm install && npm run build # Example for a Node.js project

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Replace with your desired folder name
          # publish_branch: gh-pages # The branch where the static site will be published